---
title: "Related resources delivered by EU eLTER sites"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Related resources delivered by EU eLTER sites}
  %\VignetteEngine{knitr::knitr}
  %\usepackage[UTF-8]{inputenc}
author: "Alessandro Oggioni"
---

```{r, child="resources_delivered_eu_networks.Rmd", include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
```

```{r}
x <- "https://deims.org/dataset/36b505da-ad12-42ad-a661-242b8fec2078"
a <- ReLTER::get_dataset_info(x) %>%
  dplyr::select(
    dateRange.from
  )
View(a)
```

```{r}
datasets_resources <- related_resources %>%
  dplyr::filter(type == "dataset")

datasets_info <- purrr::map_dfr(
  as.list(
    datasets_resources$uri[1:10]
  ),
  function (x) {
    ReLTER::get_dataset_info(x) %>%
      dplyr::mutate(
        ID = x,
        title = title,
        from = .[[6]],
        to = .[[7]],
        siteTitle = relatedSite[[1]]$title,
        siteID = paste0(relatedSite[[1]]$id$prefix, relatedSite[[1]]$id$suffix),
        DOI = doi,
        geometry = boundaries
      )
  }
) %>%
  dplyr::select(
    ID, title, from, to, siteTitle, siteID, DOI, geometry
  )

datasets_x_site <- datasets_info
```
