---
title: "ReLTER"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ReLTER}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  fig.ext = 'png',
  out.width = "100%"
)
```

## Citation of <span style="color:#2878B3;font-size:90%;font-weight:normal;">ReLTER</span>

To cite <span style="color:#2878B3;font-size:90%;font-weight:normal;">ReLTER</span> please use:
Alessandro Oggioni. (2021). oggioniale/ReLTER: v0.3.0 (0.3.0). Zenodo. https://doi.org/10.5281/zenodo.5576813

or:

``` bibtex
@software{alessandro_oggioni_2021_5576814,
  author       = {Alessandro Oggioni},
  title        = {oggioniale/ReLTER: v0.3.0},
  month        = oct,
  year         = 2021,
  publisher    = {Zenodo},
  version      = {0.2.0},
  doi          = {10.5281/zenodo.5576813},
  url          = {https://doi.org/10.5281/zenodo.5576813}
}
```

## Documentation of <span style="color:#2878B3;font-size:90%;font-weight:normal;">ReLTER</span>

You can visit <span style="color:#2878B3;font-size:90%;font-weight:normal;">ReLTER</span> website at [oggioniale.github.io/ReLTER/](https://oggioniale.github.io/ReLTER/) for obtain documentation about installation and examples of use.


## Installation of <span style="color:#2878B3;font-size:90%;font-weight:normal;">ReLTER</span>

You can install the development version of <span style="color:#2878B3;font-size:90%;font-weight:normal;">ReLTER</span> from [GitHub](https://github.com/oggioniale/ReLTER) with:

```{r, installationInfo, eval = FALSE}
install.packages("devtools")
devtools::install_github("oggioniale/ReLTER")
```



