#' Obtain the observations from a sensor.
#' @description `r lifecycle::badge("experimental")`
#' This function obtains the observations shared by
#' procedure/sensor through Sensor Observation Service (SOS).
#' @param procedure A `character`. It is a procedure/sensor ID.
#' @param sosURL A `character`. The endpoint of the Sensor Observation Service
#' (SOS) service.
#' @return The output of the function is a `sf` of observations shared by
#' procedure/sensor through Sensor Observation Service (SOS). The table
#' contains SRS (Spatial Reference System) of the feature where the
#' observations are collected, the ID of the feature, the geometry of the
#' feature, and all the observed properties (e.g. phenomenonTime and
#' Air_Temperature) provided by the sensor. The observed properties are
#' enriched by the semantic link, as provided by SOS.
#' For the Unit Of Measurement (UOM) assigned to the observed properties
#' the labeling is generated by R package
#' \href{https://r-quantities.github.io/units/index.html}{`units`}
#' \insertCite{@ @utilsR}{ReLTER} in order
#' to simplify the propagation, conversation and derivation of units of
#' collected observations.
#' @author Alessandro Oggioni, phD (2020) \email{oggioni.a@@irea.cnr.it}
#' @author Paolo Tagliolato, PhD (2021) \email{tagliolato.p@@irea.cnr.it}
#' @importFrom sos4R SOS sosOfferings getObservation sosProcedures sosBoundedBy
#' @importFrom sos4R sosResult
#' @importFrom units set_units
#' @importFrom dplyr arrange
#' @importFrom tibble as_tibble
#' @importFrom sf st_as_sf st_bbox st_as_sfc
#' @importFrom leaflet leaflet addTiles addPolygons
#' @importFrom Rdpack reprompt
#' @references
#'   \insertRef{utilsR}{ReLTER}
#' @export
#' @examples
#' FP <- get_sos_obs(
#'   sosURL = "http://getit.lteritalia.it/observations/service",
#'   procedure = "http://www.get-it.it/sensors/getit.lteritalia.it/procedure/noOwnerDeclared/noModelDeclared/noSerialNumberDeclared/1286194C-A5DF-11DF-8ED7-1602DFD72097",
#'   show_map = FALSE
#' )
#' FP
#' 
#' # MONALISA EURAC research
#' get_sos_obs(
#'   sosURL = "http://monalisasos.eurac.edu/sos/service",
#'   procedure = "QuantumSensor_nemef2000",
#'   show_map = FALSE
#' )
#' 
#' # Air temperature sensor
#' airTemp <- get_sos_obs(
#'   sosURL = "http://getit.lteritalia.it/observations/service",
#'   procedure = "http://www.get-it.it/sensors/getit.lteritalia.it/procedure/noOwnerDeclared/noModelDeclared/noSerialNumberDeclared/SI000049-1675AirTemp",
#'   show_map = TRUE
#' )
#' airTemp
#' 
#' # about units of measurement (UOM)
#'  # the UOM of this observed property is °C
#' airTemp$Air_Temperature
#' # is is easily convert to °F
#' units::set_units(airTemp$Air_Temperature, "°F")
#' 
#' # about semantic enrichment
#' # the URI of the label of first two columns
#' # of `airTemp`
#' attributes(airTemp)$uri 
#'
### function get_sos_obs

# procedure <- "http://www.get-it.it/sensors/getit.lteritalia.it/procedure/noOwnerDeclared/noModelDeclared/noSerialNumberDeclared/1286194C-A5DF-11DF-8ED7-1602DFD72097"
# sosURL <- "http://getit.lteritalia.it/observations/service"
# mySos <- sos4R::SOS(
#   url = sosURL,
#   binding = "KVP",
#   version = "2.0.0"
# )
# siteList <- sos4R::siteList(sos = mySos)
# sos4R::phenomena(sos = mySos)
# data2 <- sos4R::getData(sos = mySos,
#                phenomena = "http://vocabs.lter-europe.net/EnvThes/20166",
#                sites = siteList[c(9:10),1]
# )
# data2
# unique(data2$siteID)

get_sos_obs_sos4R <- function(sosURL, procedure, show_map = FALSE) {
  mySos <- sos4R::SOS(
    url = sosURL,
    binding = "KVP",
    useDCPs = FALSE
  )
  # Offerings ----
  offerings <- sos4R::sosOfferings(mySos)
  offering <- offerings[sapply(
    offerings,
    function(x) x@procedure == procedure
  )]
  # Procedure info ----
  proc101 <- sos4R::describeSensor(
    sos = mySos,
    procedure = procedure,
    outputFormat = 'text/xml; subtype="sensorML/1.0.1"'
  )
  proc <- sos4R::describeSensor(
    sos = mySos,
    procedure = procedure,
    outputFormat = 'text/xml; subtype="sensorml/2.0"'
  )
  proc@id <- proc101@id
  proc@name <- xml2::xml_text(
    xml2::xml_find_all(
      proc@xml,
      ".//gml:name"
    )
  )
  proc@description <- xml2::xml_text(
    xml2::xml_find_all(
      proc@xml,
      ".//gml:description"
    )
  )
  proc@boundedBy <- proc101@boundedBy
  proc@coords <- proc101@coords
  # Observations and results ----
  if (length(offering) == 0) {
    obsBbox <- NA
    results <- NA
  } else {
    obs <- sos4R::getObservation(
      sos = mySos,
      offering = offering[[1]]@id,
      procedure = sos4R::sosProcedures(offering),
      verbose = FALSE
    )
    obsBbox <- sos4R::sosBoundedBy(obs, bbox = TRUE)
    obsCRS <- sos4R::sosBoundedBy(obs)$srsName
    nMembers <- length(obs@members)
    results <- list()
    for (m in 1:nMembers) {
      nameMember <- paste0("obsMember_", m)
      tmp <- list(
        sos4R::sosResult(
          obs@members[[m]],
          coordinates = TRUE
        ) %>%
          sf::st_as_sf(
            coords = c("lon", "lat"),
            crs = obsCRS
          )
      )
      results[[nameMember]] <- tmp
    }
    resultPoints <- list()
    for (n in 1:length(results)) {
      tmp <- results[[n]][[1]] %>%
        dplyr::select(geometry) %>%
        dplyr::slice(1)
      resultPoints[[n]] <- tmp
    }
    obsProps <- get_sensor_observed_properties(
      sosURL = sosURL,
      procedure = procedure
    )
    # observations for feature ----
    numObsForFeature <- table(results$feature)

    # add sampledFeature the feature with FOIs URI ----
    FOIsTibble <- tibble::tibble(
      sampledFeature = as.character(),
      feature = as.character()
    )
    for (l in 1:length(obs@members[[1]]@featureOfInterest@feature@sampledFeatures)) {
      sampledFeature <- obs@members[[1]]@featureOfInterest@feature@sampledFeatures[[l]]
      feature <- obs@members[[1]]@featureOfInterest@feature@id[[l]]
      FOIsTibble <- FOIsTibble %>%
        tibble::add_row(
          tibble::tibble_row(
            sampledFeature = sampledFeature,
            feature = feature
          )
        )
    }
    results <- dplyr::left_join(
      x = results,
      y = FOIsTibble,
      by = "feature"
    )
    

    # Definition semantic enrichment ----
    attr(
      x = results,
      which = "uri"
    ) <- obsProps$obsProURI

    # UOM from QUDT ----
    for (i in 1:nrow(obsProps)) {
      if (obsProps$obsProQudtCode[i] == "") {
        next
      } else {
        attrName <- obsProps$obsProLabel[i]
        results <- results %>%
          dplyr::mutate(
            !!attrName := units::set_units(
              eval(parse(text = attrName)),
              obsProps$obsProQudtCode[i],
              mode = "standard"
            )
          )
      }
    }
  }

  if (!is.na(results)) {
    if (any(names(results) == "phenomenonTime")) {
      results <- results %>% 
        dplyr::arrange(phenomenonTime)
      results
    } else {
      results
    }
  } else {
    results <- NA
    results
    message(
      "\n----\n",
      "This sensor does not have collectes or provides observations yet.\n",
      "----\n"
    )
  }

  # info geo offering ----
  if (is.na(obsBbox)) {
    obsBboxGeo <- NULL
    if (show_map == TRUE) {
      message(
        "\n----\n",
        "This sensor does not have collectes or provides observations yet.\n",
        "The map relating to the distribution of observations cannot",
        "be drawn.\n",
        "----\n"
      )
    }
  } else {
    obsBboxGeo <- obsBbox %>%
      t(.) %>%
      tibble::as_tibble() %>%
      sf::st_as_sf(
        coords = c("coords.lon", "coords.lat"),
        crs = obsCRS
      ) %>%
      sf::st_bbox() %>% 
      sf::st_as_sfc()

    if (show_map == TRUE) {
      map <- leaflet::leaflet() %>%
        leaflet::addTiles() %>%
        leaflet::addPolygons(
          data = obsBboxGeo,
          color = "red",
          weight = 2,
          opacity = 0.5,
          fill = TRUE,
          fillColor = "red",
          fillOpacity = 0.2
        ) %>%
        leaflet::addMarkers(
          data = resultPoints,
          popup = paste0(
            "<b>Sensor name: </b>",
            "<br>",
            "<a href='",
            proc@id,
            "' target='_blank'>",
            proc@name,
            "</a>",
            "<br>",
            "<b>Sensor coordinates: </b>",
            "<br>",
            "Lon: ", proc@coords$Lon,
            " - ",
            "Lat: ", proc@coords$Lat,
            "<br>",
            "<b>Observations from this sensor: </b>",
            numObsForFeature
          )
        )
      print(map)
    }
  }

  return(results)
}
