name: test-coverage

on:
  push:
    branches: [main, dev, dev-OggioniAle]
  pull_request:
    branches: [main, dev, dev-OggioniAle]

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      LOCAL_DEIMS: false

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # Install system dependencies (come nel Dockerfile)
      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libudunits2-dev \
            libgdal-dev \
            libgeos-dev \
            libproj-dev \
            libfontconfig1-dev \
            libjq-dev \
            libv8-dev \
            libgit2-dev \
            build-essential \
            gfortran \
            libglpk-dev

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
          needs: coverage

      - name: Test coverage
        run: covr::codecov(quiet = FALSE)
        shell: Rscript {0}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}